#5819 Replaced all nose.tools.assert_almost_equal with similar method from numpy instead. Reason is that nosetests seems to fail due to bug:
TypeError: type numpy.ndarray doesn't define __round__ method